export const DIAGNOSIS_CATALOG = [
  // ─── Respiratory (~40) ──────────────────────────────────────────
  { code: 'J00',   label: 'Acute nasopharyngitis (common cold)', category: 'respiratory' },
  { code: 'J02.9', label: 'Acute pharyngitis, unspecified', category: 'respiratory' },
  { code: 'J03.9', label: 'Acute tonsillitis, unspecified', category: 'respiratory' },
  { code: 'J04.0', label: 'Acute laryngitis', category: 'respiratory' },
  { code: 'J04.1', label: 'Acute tracheitis', category: 'respiratory' },
  { code: 'J06.9', label: 'Acute upper respiratory infection, unspecified', category: 'respiratory' },
  { code: 'J11.1', label: 'Influenza with respiratory manifestations', category: 'respiratory' },
  { code: 'J11.8', label: 'Influenza with other manifestations', category: 'respiratory' },
  { code: 'J20.9', label: 'Acute bronchitis, unspecified', category: 'respiratory' },
  { code: 'J21.9', label: 'Acute bronchiolitis, unspecified', category: 'respiratory' },
  { code: 'J39.9', label: 'Upper respiratory infection, unspecified site', category: 'respiratory' },
  { code: 'J45.9', label: 'Asthma, unspecified', category: 'respiratory' },
  { code: 'J45.0', label: 'Asthma with status asthmaticus', category: 'respiratory' },
  { code: 'J44.9', label: 'COPD, unspecified', category: 'respiratory' },
  { code: 'J44.1', label: 'COPD with acute exacerbation', category: 'respiratory' },
  { code: 'J18.9', label: 'Pneumonia, unspecified organism', category: 'respiratory' },
  { code: 'J18.1', label: 'Lobar pneumonia, unspecified organism', category: 'respiratory' },
  { code: 'J13',   label: 'Pneumococcal pneumonia', category: 'respiratory' },
  { code: 'J15.0', label: 'Klebsiella pneumonia', category: 'respiratory' },
  { code: 'J15.7', label: 'Mycoplasma pneumonia', category: 'respiratory' },
  { code: 'J15.9', label: 'Bacterial pneumonia, unspecified', category: 'respiratory' },
  { code: 'J20.5', label: 'Acute bronchitis due to respiratory syncytial virus', category: 'respiratory' },
  { code: 'J40',   label: 'Bronchitis, not specified as acute or chronic', category: 'respiratory' },
  { code: 'J42',   label: 'Unspecified chronic bronchitis', category: 'respiratory' },
  { code: 'J43.9', label: 'Emphysema, unspecified', category: 'respiratory' },
  { code: 'J47.9', label: 'Bronchiectasis, unspecified', category: 'respiratory' },
  { code: 'J81.0', label: 'Acute pulmonary edema', category: 'respiratory' },
  { code: 'J84.10', label: 'Pulmonary fibrosis, unspecified', category: 'respiratory' },
  { code: 'J90',   label: 'Pleural effusion, not elsewhere classified', category: 'respiratory' },
  { code: 'J93.0', label: 'Spontaneous tension pneumothorax', category: 'respiratory' },
  { code: 'J93.9', label: 'Pneumothorax, unspecified', category: 'respiratory' },
  { code: 'J86.0', label: 'Pyothorax with fistula', category: 'respiratory' },
  { code: 'J86.9', label: 'Pyothorax without fistula (empyema)', category: 'respiratory' },
  { code: 'J91',   label: 'Pleural effusion in conditions classified elsewhere', category: 'respiratory' },
  { code: 'J98.11', label: 'Atelectasis', category: 'respiratory' },
  { code: 'J38.4', label: 'Laryngeal spasm', category: 'respiratory' },
  { code: 'J34.2', label: 'Deviated nasal septum', category: 'respiratory' },
  { code: 'J33.9', label: 'Nasal polyp, unspecified', category: 'respiratory' },
  { code: 'J01.9', label: 'Acute sinusitis, unspecified', category: 'respiratory' },
  { code: 'J32.9', label: 'Chronic sinusitis, unspecified', category: 'respiratory' },
  { code: 'J37.0', label: 'Chronic laryngitis', category: 'respiratory' },
  { code: 'J38.1', label: 'Polyp of vocal cord/larynx', category: 'respiratory' },

  // ─── Cardiovascular (~35) ────────────────────────────────────────
  { code: 'I10',   label: 'Essential (primary) hypertension', category: 'cardiovascular' },
  { code: 'I11.9', label: 'Hypertensive heart disease without heart failure', category: 'cardiovascular' },
  { code: 'I11.0', label: 'Hypertensive heart disease with heart failure', category: 'cardiovascular' },
  { code: 'I12.9', label: 'Hypertensive chronic kidney disease', category: 'cardiovascular' },
  { code: 'I13.9', label: 'Hypertensive heart and kidney disease', category: 'cardiovascular' },
  { code: 'I15.9', label: 'Secondary hypertension, unspecified', category: 'cardiovascular' },
  { code: 'I16.0', label: 'Hypertensive urgency', category: 'cardiovascular' },
  { code: 'I16.1', label: 'Hypertensive emergency', category: 'cardiovascular' },
  { code: 'I20.8', label: 'Angina pectoris, other forms (stable)', category: 'cardiovascular' },
  { code: 'I20.0', label: 'Unstable angina', category: 'cardiovascular' },
  { code: 'I20.9', label: 'Angina pectoris, unspecified', category: 'cardiovascular' },
  { code: 'I21.9', label: 'Acute myocardial infarction, unspecified', category: 'cardiovascular' },
  { code: 'I21.4', label: 'Non-ST elevation (NSTEMI) myocardial infarction', category: 'cardiovascular' },
  { code: 'I21.0', label: 'ST elevation (STEMI) myocardial infarction of anterior wall', category: 'cardiovascular' },
  { code: 'I21.1', label: 'ST elevation (STEMI) myocardial infarction of inferior wall', category: 'cardiovascular' },
  { code: 'I22.9', label: 'Subsequent myocardial infarction, unspecified', category: 'cardiovascular' },
  { code: 'I25.1', label: 'Atherosclerotic heart disease', category: 'cardiovascular' },
  { code: 'I25.9', label: 'Chronic ischemic heart disease, unspecified', category: 'cardiovascular' },
  { code: 'I25.10', label: 'Atherosclerotic heart disease of native coronary artery', category: 'cardiovascular' },
  { code: 'I50.1', label: 'Left ventricular failure', category: 'cardiovascular' },
  { code: 'I50.9', label: 'Heart failure, unspecified', category: 'cardiovascular' },
  { code: 'I50.22', label: 'Chronic systolic (congestive) heart failure', category: 'cardiovascular' },
  { code: 'I50.32', label: 'Chronic diastolic (congestive) heart failure', category: 'cardiovascular' },
  { code: 'I50.43', label: 'Acute on chronic combined systolic and diastolic heart failure', category: 'cardiovascular' },
  { code: 'I48',   label: 'Atrial fibrillation and flutter', category: 'cardiovascular' },
  { code: 'I47.1', label: 'Supraventricular tachycardia', category: 'cardiovascular' },
  { code: 'I47.2', label: 'Ventricular tachycardia', category: 'cardiovascular' },
  { code: 'I44.2', label: 'Atrioventricular block, complete', category: 'cardiovascular' },
  { code: 'I49.5', label: 'Sick sinus syndrome', category: 'cardiovascular' },
  { code: 'I27.81', label: 'Cor pulmonale (chronic)', category: 'cardiovascular' },
  { code: 'I05.0', label: 'Mitral stenosis', category: 'cardiovascular' },
  { code: 'I34.0', label: 'Mitral (nonrheumatic) insufficiency', category: 'cardiovascular' },
  { code: 'I35.0', label: 'Nonrheumatic aortic (valve) stenosis', category: 'cardiovascular' },
  { code: 'I35.1', label: 'Nonrheumatic aortic (valve) insufficiency', category: 'cardiovascular' },
  { code: 'I33.0', label: 'Acute and subacute infective endocarditis', category: 'cardiovascular' },
  { code: 'I30.9', label: 'Acute pericarditis, unspecified', category: 'cardiovascular' },
  { code: 'I31.3', label: 'Pericardial effusion (noninflammatory)', category: 'cardiovascular' },
  { code: 'I42.0', label: 'Dilated cardiomyopathy', category: 'cardiovascular' },
  { code: 'I42.2', label: 'Other hypertrophic cardiomyopathy', category: 'cardiovascular' },
  { code: 'I80.2', label: 'Phlebitis and thrombophlebitis of other deep vessels (DVT)', category: 'cardiovascular' },
  { code: 'I26.9', label: 'Pulmonary embolism without acute cor pulmonale', category: 'cardiovascular' },
  { code: 'I71.4', label: 'Abdominal aortic aneurysm, without rupture', category: 'cardiovascular' },
  { code: 'I77.9', label: 'Disorder of arteries and arterioles, unspecified', category: 'cardiovascular' },

  // ─── Endocrine / Metabolic (~25) ─────────────────────────────────
  { code: 'E11.9', label: 'Type 2 diabetes mellitus without complications', category: 'endocrine' },
  { code: 'E11.65', label: 'Type 2 diabetes mellitus with hyperglycemia', category: 'endocrine' },
  { code: 'E11.40', label: 'Type 2 diabetes mellitus with diabetic neuropathy', category: 'endocrine' },
  { code: 'E11.22', label: 'Type 2 diabetes mellitus with diabetic nephropathy', category: 'endocrine' },
  { code: 'E11.31', label: 'Type 2 diabetes mellitus with diabetic retinopathy', category: 'endocrine' },
  { code: 'E11.621', label: 'Type 2 diabetes mellitus with foot ulcer', category: 'endocrine' },
  { code: 'E11.10', label: 'Type 2 diabetes mellitus with ketoacidosis', category: 'endocrine' },
  { code: 'E11.00', label: 'Type 2 diabetes mellitus with hyperosmolarity', category: 'endocrine' },
  { code: 'E10.9', label: 'Type 1 diabetes mellitus without complications', category: 'endocrine' },
  { code: 'E10.10', label: 'Type 1 diabetes mellitus with ketoacidosis', category: 'endocrine' },
  { code: 'O24.4', label: 'Gestational diabetes mellitus', category: 'endocrine' },
  { code: 'E16.2', label: 'Hypoglycemia, unspecified', category: 'endocrine' },
  { code: 'E03.9', label: 'Hypothyroidism, unspecified', category: 'endocrine' },
  { code: 'E03.0', label: 'Congenital hypothyroidism', category: 'endocrine' },
  { code: 'E05.9', label: 'Thyrotoxicosis [hyperthyroidism], unspecified', category: 'endocrine' },
  { code: 'E05.0', label: 'Thyrotoxicosis with diffuse goiter (Graves disease)', category: 'endocrine' },
  { code: 'E04.0', label: 'Nontoxic diffuse goiter', category: 'endocrine' },
  { code: 'E04.1', label: 'Nontoxic single thyroid nodule', category: 'endocrine' },
  { code: 'E04.2', label: 'Nontoxic multinodular goiter', category: 'endocrine' },
  { code: 'E06.9', label: 'Thyroiditis, unspecified', category: 'endocrine' },
  { code: 'E06.3', label: 'Thyroiditis, chronic (Hashimoto)', category: 'endocrine' },
  { code: 'E24.9', label: "Cushing's syndrome, unspecified", category: 'endocrine' },
  { code: 'E27.1', label: "Primary adrenocortical insufficiency (Addison)", category: 'endocrine' },
  { code: 'E78.5', label: 'Hyperlipidemia, unspecified', category: 'endocrine' },
  { code: 'E55.9', label: 'Vitamin D deficiency, unspecified', category: 'endocrine' },
  { code: 'E53.9', label: 'Vitamin B deficiency, unspecified', category: 'endocrine' },
  { code: 'E56.9', label: 'Vitamin deficiency, unspecified', category: 'endocrine' },
  { code: 'E83.42', label: 'Zinc deficiency', category: 'endocrine' },

  // ─── Gastrointestinal (~35) ──────────────────────────────────────
  { code: 'K29.7', label: 'Gastritis, unspecified', category: 'gastrointestinal' },
  { code: 'K29.0', label: 'Acute gastritis', category: 'gastrointestinal' },
  { code: 'K29.5', label: 'Chronic gastritis, unspecified', category: 'gastrointestinal' },
  { code: 'K21.9', label: 'Gastro-esophageal reflux disease (GERD) without esophagitis', category: 'gastrointestinal' },
  { code: 'K21.0', label: 'Gastro-esophageal reflux disease (GERD) with esophagitis', category: 'gastrointestinal' },
  { code: 'K25.9', label: 'Gastric ulcer, unspecified', category: 'gastrointestinal' },
  { code: 'K26.9', label: 'Duodenal ulcer, unspecified', category: 'gastrointestinal' },
  { code: 'K27.9', label: 'Peptic ulcer, site unspecified', category: 'gastrointestinal' },
  { code: 'K27.3', label: 'Acute peptic ulcer without perforation or bleeding', category: 'gastrointestinal' },
  { code: 'K27.4', label: 'Chronic peptic ulcer without perforation or bleeding', category: 'gastrointestinal' },
  { code: 'K92.0', label: 'Hematemesis (vomiting blood)', category: 'gastrointestinal' },
  { code: 'K92.1', label: 'Melena (blood in stool)', category: 'gastrointestinal' },
  { code: 'K92.2', label: 'Gastrointestinal hemorrhage, unspecified', category: 'gastrointestinal' },
  { code: 'K30',   label: 'Functional dyspepsia', category: 'gastrointestinal' },
  { code: 'K58.9', label: 'Irritable bowel syndrome (IBS), unspecified', category: 'gastrointestinal' },
  { code: 'K50.9', label: "Crohn's disease, unspecified", category: 'gastrointestinal' },
  { code: 'K51.9', label: 'Ulcerative colitis, unspecified', category: 'gastrointestinal' },
  { code: 'K80.2', label: 'Calculus of gallbladder without cholecystitis (gallstones)', category: 'gastrointestinal' },
  { code: 'K81.0', label: 'Acute cholecystitis', category: 'gastrointestinal' },
  { code: 'K81.9', label: 'Cholecystitis, unspecified', category: 'gastrointestinal' },
  { code: 'K85.9', label: 'Acute pancreatitis, unspecified', category: 'gastrointestinal' },
  { code: 'K86.1', label: 'Chronic pancreatitis', category: 'gastrointestinal' },
  { code: 'K74.6', label: 'Other and unspecified cirrhosis of liver', category: 'gastrointestinal' },
  { code: 'K72.90', label: 'Hepatic failure, unspecified', category: 'gastrointestinal' },
  { code: 'K70.9', label: 'Alcoholic liver disease, unspecified', category: 'gastrointestinal' },
  { code: 'K76.0', label: 'Fatty (change of) liver, not elsewhere classified (NAFLD)', category: 'gastrointestinal' },
  { code: 'K35.80', label: 'Unspecified acute appendicitis', category: 'gastrointestinal' },
  { code: 'K35.2', label: 'Acute appendicitis with generalized peritonitis', category: 'gastrointestinal' },
  { code: 'K56.6', label: 'Unspecified intestinal obstruction', category: 'gastrointestinal' },
  { code: 'K65.9', label: 'Peritonitis, unspecified', category: 'gastrointestinal' },
  { code: 'K63.1', label: 'Perforation of intestine (nontraumatic)', category: 'gastrointestinal' },
  { code: 'K59.0', label: 'Constipation', category: 'gastrointestinal' },
  { code: 'K64.9', label: 'Hemorrhoids, unspecified', category: 'gastrointestinal' },
  { code: 'K60.2', label: 'Anal fissure, unspecified', category: 'gastrointestinal' },
  { code: 'K40.9', label: 'Inguinal hernia, without obstruction or gangrene', category: 'gastrointestinal' },
  { code: 'K43.9', label: 'Umbilical hernia without obstruction or gangrene', category: 'gastrointestinal' },
  { code: 'K42.9', label: 'Incisional hernia without obstruction', category: 'gastrointestinal' },
  { code: 'K22.7', label: "Barrett's esophagus", category: 'gastrointestinal' },
  { code: 'K22.10', label: 'Ulcer of esophagus, unspecified', category: 'gastrointestinal' },
  { code: 'K57.90', label: 'Diverticulosis of intestine, unspecified', category: 'gastrointestinal' },

  // ─── Infectious Diseases — Kenya Specific (~50) ──────────────────
  { code: 'B54',   label: 'Malaria, unspecified', category: 'infectious' },
  { code: 'B50.9', label: 'Plasmodium falciparum malaria, unspecified', category: 'infectious' },
  { code: 'B50.0', label: 'Cerebral malaria (P. falciparum)', category: 'infectious' },
  { code: 'B51.9', label: 'Plasmodium vivax malaria, unspecified', category: 'infectious' },
  { code: 'B52.9', label: 'Plasmodium malariae malaria, unspecified', category: 'infectious' },
  { code: 'B53.0', label: 'Plasmodium ovale malaria', category: 'infectious' },
  { code: 'A01.0', label: 'Typhoid fever', category: 'infectious' },
  { code: 'A01.4', label: 'Paratyphoid fever, unspecified', category: 'infectious' },
  { code: 'A00.0', label: 'Cholera due to Vibrio cholerae 01, biovar cholerae', category: 'infectious' },
  { code: 'A09',   label: 'Infectious gastroenteritis and colitis, unspecified', category: 'infectious' },
  { code: 'A03.9', label: 'Shigellosis, unspecified (bacillary dysentery)', category: 'infectious' },
  { code: 'A06.0', label: 'Acute amebic dysentery', category: 'infectious' },
  { code: 'A15.0', label: 'Tuberculosis of lung, confirmed by sputum smear', category: 'infectious' },
  { code: 'A15.5', label: 'Tuberculosis of larynx, trachea, bronchus', category: 'infectious' },
  { code: 'A15.6', label: 'Tuberculous pleurisy', category: 'infectious' },
  { code: 'A18.2', label: 'Tuberculous peripheral lymphadenopathy', category: 'infectious' },
  { code: 'A18.01', label: "Tuberculosis of spine (Pott's disease)", category: 'infectious' },
  { code: 'A17.0', label: 'Tuberculous meningitis', category: 'infectious' },
  { code: 'A18.9', label: 'Tuberculosis, extrapulmonary, unspecified', category: 'infectious' },
  { code: 'Z21',   label: 'Asymptomatic HIV infection status', category: 'infectious' },
  { code: 'B20',   label: 'HIV disease resulting in infectious/parasitic diseases (AIDS)', category: 'infectious' },
  { code: 'B24',   label: 'Unspecified HIV disease', category: 'infectious' },
  { code: 'B37.0', label: 'Candidiasis of mouth (oral thrush)', category: 'infectious' },
  { code: 'B37.81', label: 'Candidiasis of esophagus', category: 'infectious' },
  { code: 'B37.3', label: 'Candidiasis of vulva and vagina', category: 'infectious' },
  { code: 'B59',   label: 'Pneumocystosis (PCP)', category: 'infectious' },
  { code: 'C46.9', label: "Kaposi's sarcoma, unspecified", category: 'infectious' },
  { code: 'B58.2', label: 'Toxoplasmosis (cerebral)', category: 'infectious' },
  { code: 'B45.1', label: 'Cerebral cryptococcosis', category: 'infectious' },
  { code: 'B00.1', label: 'Herpesviral vesicular dermatitis', category: 'infectious' },
  { code: 'B02.9', label: 'Zoster [shingles] without complications', category: 'infectious' },
  { code: 'B01.9', label: 'Varicella [chickenpox] without complication', category: 'infectious' },
  { code: 'B05.9', label: 'Measles without complication', category: 'infectious' },
  { code: 'B26.9', label: 'Mumps without complication', category: 'infectious' },
  { code: 'B06.9', label: 'Rubella [German measles] without complication', category: 'infectious' },
  { code: 'A51.0', label: 'Primary syphilis', category: 'infectious' },
  { code: 'A51.3', label: 'Secondary syphilis', category: 'infectious' },
  { code: 'A51.5', label: 'Late syphilis, latent', category: 'infectious' },
  { code: 'A54.0', label: 'Gonococcal infection of lower genitourinary tract', category: 'infectious' },
  { code: 'A56.0', label: 'Chlamydial infection of lower genitourinary tract', category: 'infectious' },
  { code: 'A57',   label: 'Chancroid', category: 'infectious' },
  { code: 'A60.0', label: 'Herpesviral infection of genitalia', category: 'infectious' },
  { code: 'A55',   label: 'Lymphogranuloma venereum', category: 'infectious' },
  { code: 'A59.0', label: 'Trichomoniasis of urogenital tract', category: 'infectious' },
  { code: 'N76.1', label: 'Bacterial vaginosis (noninfectious)', category: 'infectious' },
  { code: 'A39.0', label: 'Meningococcal meningitis', category: 'infectious' },
  { code: 'A39.2', label: 'Acute meningococcemia', category: 'infectious' },
  { code: 'A40.9', label: 'Streptococcal sepsis, unspecified', category: 'infectious' },
  { code: 'A41.9', label: 'Sepsis, unspecified organism', category: 'infectious' },
  { code: 'R65.21', label: 'Severe sepsis with septic shock', category: 'infectious' },
  { code: 'A23.9', label: 'Brucellosis, unspecified', category: 'infectious' },
  { code: 'A27.9', label: 'Leptospirosis, unspecified', category: 'infectious' },
  { code: 'A33',   label: 'Tetanus neonatorum', category: 'infectious' },
  { code: 'A34',   label: 'Obstetrical tetanus', category: 'infectious' },
  { code: 'A35',   label: 'Other tetanus', category: 'infectious' },
  { code: 'A82.9', label: 'Rabies, unspecified', category: 'infectious' },
  { code: 'A90',   label: 'Dengue fever [classical dengue]', category: 'infectious' },
  { code: 'A91',   label: 'Dengue hemorrhagic fever', category: 'infectious' },
  { code: 'A95',   label: 'Yellow fever', category: 'infectious' },
  { code: 'A30.9', label: 'Leprosy, unspecified', category: 'infectious' },
  { code: 'A77.9', label: 'Spotted fever (rickettsiosis), unspecified', category: 'infectious' },
  { code: 'B65.0', label: 'Schistosomiasis due to Schistosoma haematobium', category: 'infectious' },
  { code: 'B65.1', label: 'Schistosomiasis due to Schistosoma mansoni', category: 'infectious' },
  { code: 'B77.9', label: 'Ascariasis (roundworm)', category: 'infectious' },
  { code: 'B76.9', label: 'Hookworm disease, unspecified', category: 'infectious' },
  { code: 'B80',   label: 'Enterobiasis (pinworm)', category: 'infectious' },
  { code: 'B68.9', label: 'Taeniasis, unspecified (tapeworm)', category: 'infectious' },
  { code: 'B74.9', label: 'Filariasis, unspecified', category: 'infectious' },
  { code: 'B73.9', label: 'Onchocerciasis (river blindness)', category: 'infectious' },
  { code: 'B55.1', label: 'Cutaneous leishmaniasis', category: 'infectious' },
  { code: 'B55.0', label: 'Visceral leishmaniasis (kala-azar)', category: 'infectious' },

  // ─── Neurological (~30) ──────────────────────────────────────────
  { code: 'G43.909', label: 'Migraine, unspecified, not intractable, without status', category: 'neurological' },
  { code: 'G43.109', label: 'Migraine with aura, not intractable, without status', category: 'neurological' },
  { code: 'G43.209', label: 'Migraine without aura, not intractable, without status', category: 'neurological' },
  { code: 'G44.2',  label: 'Tension-type headache', category: 'neurological' },
  { code: 'G44.0',  label: 'Cluster headache syndrome', category: 'neurological' },
  { code: 'R51',    label: 'Headache', category: 'neurological' },
  { code: 'G45.9',  label: 'Transient cerebral ischemic attack, unspecified', category: 'neurological' },
  { code: 'I63.9',  label: 'Cerebral infarction, unspecified (ischemic stroke)', category: 'neurological' },
  { code: 'I61.9',  label: 'Nontraumatic intracerebral hemorrhage, unspecified', category: 'neurological' },
  { code: 'I62.9',  label: 'Nontraumatic intracranial hemorrhage, unspecified', category: 'neurological' },
  { code: 'I69.3',  label: 'Sequelae of cerebral infarction', category: 'neurological' },
  { code: 'G40.909', label: 'Epilepsy, unspecified, not intractable', category: 'neurological' },
  { code: 'G40.109', label: 'Localization-related epilepsy, not intractable', category: 'neurological' },
  { code: 'G40.309', label: 'Generalized idiopathic epilepsy, not intractable', category: 'neurological' },
  { code: 'R56.0',  label: 'Febrile convulsions', category: 'neurological' },
  { code: 'R56.9',  label: 'Unspecified convulsions', category: 'neurological' },
  { code: 'G20',    label: "Parkinson's disease", category: 'neurological' },
  { code: 'G30.9',  label: "Alzheimer's disease, unspecified", category: 'neurological' },
  { code: 'F03.90', label: 'Unspecified dementia without behavioral disturbance', category: 'neurological' },
  { code: 'G35',    label: 'Multiple sclerosis', category: 'neurological' },
  { code: 'G61.0',  label: "Guillain-Barre syndrome", category: 'neurological' },
  { code: 'G71.0',  label: 'Muscular dystrophy', category: 'neurological' },
  { code: 'G80.9',  label: 'Cerebral palsy, unspecified', category: 'neurological' },
  { code: 'G71.11', label: 'Myasthenia gravis', category: 'neurological' },
  { code: 'G44.309', label: 'Post-traumatic headache, unspecified, not intractable', category: 'neurological' },
  { code: 'G50.0',  label: "Trigeminal nerve disorder (trigeminal neuralgia)", category: 'neurological' },
  { code: 'G62.9',  label: 'Polyneuropathy, unspecified', category: 'neurological' },
  { code: 'G54.0',  label: 'Brachial plexus disorders', category: 'neurological' },
  { code: 'G57.90', label: 'Mononeuropathy of lower limb, unspecified', category: 'neurological' },
  { code: 'G56.90', label: 'Mononeuropathy of upper limb, unspecified', category: 'neurological' },
  { code: 'H81.11', label: 'Benign paroxysmal vertigo (BPPV)', category: 'neurological' },
  { code: 'H81.09', label: "Meniere's disease, unspecified ear", category: 'neurological' },
  { code: 'R42',    label: 'Dizziness and giddiness', category: 'neurological' },

  // ─── Musculoskeletal (~30) ───────────────────────────────────────
  { code: 'M54.5',  label: 'Low back pain', category: 'musculoskeletal' },
  { code: 'M54.9',  label: 'Backache, unspecified', category: 'musculoskeletal' },
  { code: 'M25.5',  label: 'Pain in joint', category: 'musculoskeletal' },
  { code: 'M19.90', label: 'Unspecified osteoarthritis, unspecified site', category: 'musculoskeletal' },
  { code: 'M15.9',  label: 'Osteoarthritis, unspecified (generalized)', category: 'musculoskeletal' },
  { code: 'M16.9',  label: 'Osteoarthritis of knee, unspecified', category: 'musculoskeletal' },
  { code: 'M17.9',  label: 'Osteoarthritis of hip, unspecified', category: 'musculoskeletal' },
  { code: 'M13.9',  label: 'Arthritis, unspecified', category: 'musculoskeletal' },
  { code: 'M05.79', label: 'Rheumatoid arthritis with rheumatoid factor', category: 'musculoskeletal' },
  { code: 'M79.1',  label: 'Myalgia (muscle pain)', category: 'musculoskeletal' },
  { code: 'M79.7',  label: 'Fibromyalgia', category: 'musculoskeletal' },
  { code: 'M79.0',  label: 'Rheumatism, unspecified', category: 'musculoskeletal' },
  { code: 'M94.9',  label: 'Disorder of bone and cartilage, unspecified', category: 'musculoskeletal' },
  { code: 'M54.2',  label: 'Cervicalgia (neck pain)', category: 'musculoskeletal' },
  { code: 'M53.9',  label: 'Dorsopathy, unspecified', category: 'musculoskeletal' },
  { code: 'M51.9',  label: 'Intervertebral disc disorder, unspecified', category: 'musculoskeletal' },
  { code: 'M43.9',  label: 'Deforming dorsopathy, unspecified', category: 'musculoskeletal' },
  { code: 'M41.9',  label: 'Scoliosis, unspecified', category: 'musculoskeletal' },
  { code: 'M62.9',  label: 'Disorder of muscle, unspecified', category: 'musculoskeletal' },
  { code: 'M84.9',  label: 'Disorder of continuity of bone, unspecified', category: 'musculoskeletal' },
  { code: 'M86.9',  label: 'Osteomyelitis, unspecified', category: 'musculoskeletal' },
  { code: 'M72.0',  label: 'Palmar fascial fibromatosis (Dupuytren)', category: 'musculoskeletal' },
  { code: 'M77.0',  label: 'Medial epicondylitis (golfer\'s elbow)', category: 'musculoskeletal' },
  { code: 'M77.1',  label: 'Lateral epicondylitis (tennis elbow)', category: 'musculoskeletal' },
  { code: 'M65.9',  label: 'Synovitis and tenosynovitis, unspecified', category: 'musculoskeletal' },
  { code: 'M71.9',  label: 'Bursopathy, unspecified', category: 'musculoskeletal' },
  { code: 'M75.1',  label: 'Rotator cuff tear or rupture, unspecified', category: 'musculoskeletal' },
  { code: 'M20.1',  label: 'Hallux valgus (bunion)', category: 'musculoskeletal' },
  { code: 'M21.9',  label: 'Acquired deformity of limb, unspecified', category: 'musculoskeletal' },
  { code: 'M89.9',  label: 'Disorder of bone, unspecified', category: 'musculoskeletal' },

  // ─── Genitourinary (~25) ─────────────────────────────────────────
  { code: 'N39.0',  label: 'Urinary tract infection, site not specified', category: 'genitourinary' },
  { code: 'N10',    label: 'Acute tubulo-interstitial nephritis (pyelonephritis)', category: 'genitourinary' },
  { code: 'N11.9',  label: 'Chronic tubulo-interstitial nephritis, unspecified', category: 'genitourinary' },
  { code: 'N17.9',  label: 'Acute kidney failure, unspecified', category: 'genitourinary' },
  { code: 'N18.9',  label: 'Chronic kidney disease, unspecified', category: 'genitourinary' },
  { code: 'N19',    label: 'Unspecified kidney failure', category: 'genitourinary' },
  { code: 'N04.9',  label: 'Nephrotic syndrome, unspecified', category: 'genitourinary' },
  { code: 'N20.0',  label: 'Calculus of kidney', category: 'genitourinary' },
  { code: 'N20.1',  label: 'Calculus of ureter', category: 'genitourinary' },
  { code: 'N20.9',  label: 'Urinary calculus, unspecified', category: 'genitourinary' },
  { code: 'N21.0',  label: 'Calculus in bladder', category: 'genitourinary' },
  { code: 'N13.9',  label: 'Obstructive and reflux uropathy, unspecified', category: 'genitourinary' },
  { code: 'N40.1',  label: 'Benign prostatic hyperplasia', category: 'genitourinary' },
  { code: 'N41.0',  label: 'Acute prostatitis', category: 'genitourinary' },
  { code: 'N41.9',  label: 'Prostatitis, unspecified', category: 'genitourinary' },
  { code: 'N45.9',  label: 'Orchitis, unspecified', category: 'genitourinary' },
  { code: 'N52.9',  label: 'Erectile dysfunction, unspecified', category: 'genitourinary' },
  { code: 'N97.9',  label: 'Female infertility, unspecified', category: 'genitourinary' },
  { code: 'N46',    label: 'Male infertility', category: 'genitourinary' },
  { code: 'N92.0',  label: 'Excessive and frequent menstruation with regular cycle (menorrhagia)', category: 'genitourinary' },
  { code: 'N94.6',  label: 'Dysmenorrhea, unspecified', category: 'genitourinary' },
  { code: 'N91.0',  label: 'Absent menstruation (primary amenorrhea)', category: 'genitourinary' },
  { code: 'N91.5',  label: 'Absent menstruation (secondary amenorrhea)', category: 'genitourinary' },
  { code: 'N28.9',  label: 'Disorder of kidney and ureter, unspecified', category: 'genitourinary' },
  { code: 'N39.3',  label: 'Stress incontinence (female)', category: 'genitourinary' },
  { code: 'N39.4',  label: 'Urge incontinence', category: 'genitourinary' },
  { code: 'N99.1',  label: 'Postprocedural urethral stricture', category: 'genitourinary' },

  // ─── Maternal / Women's Health (~25) ─────────────────────────────
  { code: 'Z34.9',  label: 'Encounter for supervision of normal pregnancy, unspecified', category: 'maternal' },
  { code: 'O20.0',  label: 'Threatened abortion', category: 'maternal' },
  { code: 'O02.1',  label: 'Missed abortion', category: 'maternal' },
  { code: 'O03.4',  label: 'Incomplete spontaneous abortion', category: 'maternal' },
  { code: 'O00.9',  label: 'Ectopic pregnancy, unspecified', category: 'maternal' },
  { code: 'O01.9',  label: 'Hydatidiform mole, unspecified', category: 'maternal' },
  { code: 'O13',    label: 'Gestational (pregnancy-induced) hypertension', category: 'maternal' },
  { code: 'O14.0',  label: 'Mild pre-eclampsia', category: 'maternal' },
  { code: 'O14.1',  label: 'Severe pre-eclampsia', category: 'maternal' },
  { code: 'O14.2',  label: 'HELLP syndrome', category: 'maternal' },
  { code: 'O15.9',  label: 'Eclampsia, unspecified', category: 'maternal' },
  { code: 'O21.0',  label: 'Mild hyperemesis gravidarum', category: 'maternal' },
  { code: 'O21.1',  label: 'Hyperemesis gravidarum with metabolic disturbance', category: 'maternal' },
  { code: 'O42.9',  label: 'Premature rupture of membranes, unspecified', category: 'maternal' },
  { code: 'O60.0',  label: 'Preterm labor without delivery', category: 'maternal' },
  { code: 'O46.9',  label: 'Antepartum hemorrhage, unspecified', category: 'maternal' },
  { code: 'O44.0',  label: 'Placenta previa without hemorrhage', category: 'maternal' },
  { code: 'O45.9',  label: 'Premature separation of placenta, unspecified', category: 'maternal' },
  { code: 'O72.0',  label: 'Postpartum hemorrhage immediately after delivery', category: 'maternal' },
  { code: 'O85',    label: 'Puerperal sepsis', category: 'maternal' },
  { code: 'O91.1',  label: 'Mastitis associated with lactation', category: 'maternal' },
  { code: 'F53.0',  label: 'Postpartum depression', category: 'maternal' },
  { code: 'O99.013', label: 'Anemia complicating pregnancy', category: 'maternal' },
  { code: 'O23.0',  label: 'Infections of kidney in pregnancy', category: 'maternal' },
  { code: 'O23.4',  label: 'Infections of urinary tract in pregnancy', category: 'maternal' },
  { code: 'Z30.9',  label: 'Encounter for contraceptive management, unspecified', category: 'maternal' },

  // ─── Psychiatric (~25) ───────────────────────────────────────────
  { code: 'F32.9',  label: 'Major depressive disorder, single episode, unspecified', category: 'psychiatric' },
  { code: 'F33.9',  label: 'Major depressive disorder, recurrent, unspecified', category: 'psychiatric' },
  { code: 'F41.1',  label: 'Generalized anxiety disorder', category: 'psychiatric' },
  { code: 'F41.0',  label: 'Panic disorder (episodic paroxysmal anxiety)', category: 'psychiatric' },
  { code: 'F40.1',  label: 'Social phobias', category: 'psychiatric' },
  { code: 'F43.10', label: 'Post-traumatic stress disorder, unspecified', category: 'psychiatric' },
  { code: 'F43.0',  label: 'Acute stress reaction', category: 'psychiatric' },
  { code: 'F43.22', label: 'Adjustment disorder with anxiety', category: 'psychiatric' },
  { code: 'F42.9',  label: 'Obsessive-compulsive disorder, unspecified', category: 'psychiatric' },
  { code: 'F31.1',  label: 'Bipolar I disorder, manic episode, moderate', category: 'psychiatric' },
  { code: 'F31.81', label: 'Bipolar II disorder', category: 'psychiatric' },
  { code: 'F20.0',  label: 'Paranoid schizophrenia', category: 'psychiatric' },
  { code: 'F23.9',  label: 'Brief psychotic disorder, unspecified', category: 'psychiatric' },
  { code: 'R41.0',  label: 'Confusion, unspecified (delirium)', category: 'psychiatric' },
  { code: 'F10.20', label: 'Alcohol use disorder, moderate/severe', category: 'psychiatric' },
  { code: 'F11.20', label: 'Opioid use disorder, moderate/severe', category: 'psychiatric' },
  { code: 'F12.20', label: 'Cannabis use disorder, moderate/severe', category: 'psychiatric' },
  { code: 'F15.20', label: 'Other stimulant use disorder (khat/miraa)', category: 'psychiatric' },
  { code: 'F50.0',  label: 'Anorexia nervosa', category: 'psychiatric' },
  { code: 'F50.2',  label: 'Bulimia nervosa', category: 'psychiatric' },
  { code: 'R45.81', label: 'Suicidal ideation', category: 'psychiatric' },
  { code: 'F90.9',  label: 'Attention-deficit hyperactivity disorder, unspecified', category: 'psychiatric' },
  { code: 'F84.0',  label: 'Autistic disorder', category: 'psychiatric' },
  { code: 'F91.9',  label: 'Conduct disorder, unspecified', category: 'psychiatric' },
  { code: 'F45.1',  label: 'Somatic symptom disorder', category: 'psychiatric' },

  // ─── Dermatological (~25) ────────────────────────────────────────
  { code: 'L20.9',  label: 'Atopic dermatitis (eczema), unspecified', category: 'dermatological' },
  { code: 'L23.9',  label: 'Allergic contact dermatitis, unspecified', category: 'dermatological' },
  { code: 'L24.9',  label: 'Irritant contact dermatitis, unspecified', category: 'dermatological' },
  { code: 'L40.9',  label: 'Psoriasis, unspecified', category: 'dermatological' },
  { code: 'L70.0',  label: 'Acne vulgaris', category: 'dermatological' },
  { code: 'B86',    label: 'Scabies', category: 'dermatological' },
  { code: 'B85.2',  label: 'Pediculosis (lice), unspecified', category: 'dermatological' },
  { code: 'B35.4',  label: 'Tinea corporis (ringworm)', category: 'dermatological' },
  { code: 'B35.0',  label: 'Tinea capitis (scalp ringworm)', category: 'dermatological' },
  { code: 'B35.3',  label: 'Tinea pedis (athlete\'s foot)', category: 'dermatological' },
  { code: 'B35.1',  label: 'Tinea unguium (nail)', category: 'dermatological' },
  { code: 'L42',    label: 'Pityriasis rosea', category: 'dermatological' },
  { code: 'L80',    label: 'Vitiligo', category: 'dermatological' },
  { code: 'L81.1',  label: 'Melasma', category: 'dermatological' },
  { code: 'L91.0',  label: 'Hypertrophic scar / keloid', category: 'dermatological' },
  { code: 'L51.9',  label: 'Erythema multiforme, unspecified', category: 'dermatological' },
  { code: 'L51.1',  label: 'Stevens-Johnson syndrome', category: 'dermatological' },
  { code: 'L27.0',  label: 'Generalized skin eruption due to drugs (drug eruption)', category: 'dermatological' },
  { code: 'L50.0',  label: 'Acute urticaria (hives)', category: 'dermatological' },
  { code: 'L50.9',  label: 'Urticaria, unspecified', category: 'dermatological' },
  { code: 'L21.9',  label: 'Seborrheic dermatitis, unspecified', category: 'dermatological' },
  { code: 'L43.9',  label: 'Lichen planus, unspecified', category: 'dermatological' },
  { code: 'L30.9',  label: 'Dermatitis, unspecified', category: 'dermatological' },
  { code: 'L98.9',  label: 'Disorder of skin and subcutaneous tissue, unspecified', category: 'dermatological' },
  { code: 'L89.90', label: 'Pressure ulcer (decubitus), unspecified', category: 'dermatological' },
  { code: 'B07.9',  label: 'Viral wart (verruca)', category: 'dermatological' },
  { code: 'B08.1',  label: 'Molluscum contagiosum', category: 'dermatological' },

  // ─── Hematological / Oncological (~20) ───────────────────────────
  { code: 'D50.9',  label: 'Iron deficiency anemia, unspecified', category: 'hematological' },
  { code: 'D53.1',  label: 'Megaloblastic anemia (B12/folate deficiency)', category: 'hematological' },
  { code: 'D58.9',  label: 'Hemolytic anemia, unspecified', category: 'hematological' },
  { code: 'D57.1',  label: 'Sickle cell disease without crisis', category: 'hematological' },
  { code: 'D57.01', label: 'Sickle cell disease with acute pain crisis', category: 'hematological' },
  { code: 'D57.3',  label: 'Sickle cell trait', category: 'hematological' },
  { code: 'D56.3',  label: 'Thalassemia minor', category: 'hematological' },
  { code: 'D56.0',  label: 'Alpha thalassemia major', category: 'hematological' },
  { code: 'D56.1',  label: 'Beta thalassemia (major)', category: 'hematological' },
  { code: 'D61.9',  label: 'Aplastic anemia, unspecified', category: 'hematological' },
  { code: 'D69.6',  label: 'Thrombocytopenia, unspecified (ITP)', category: 'hematological' },
  { code: 'D66',    label: 'Hemophilia A', category: 'hematological' },
  { code: 'D68.01', label: 'von Willebrand disease', category: 'hematological' },
  { code: 'C95.90', label: 'Leukemia, unspecified', category: 'hematological' },
  { code: 'C81.90', label: "Hodgkin lymphoma, unspecified", category: 'hematological' },
  { code: 'C85.90', label: 'Non-Hodgkin lymphoma, unspecified', category: 'hematological' },
  { code: 'C90.00', label: 'Multiple myeloma', category: 'hematological' },
  { code: 'C50.9',  label: 'Breast cancer, unspecified (female)', category: 'hematological' },
  { code: 'C53.9',  label: 'Cervical cancer, unspecified', category: 'hematological' },
  { code: 'C61',    label: 'Prostate cancer', category: 'hematological' },
  { code: 'C22.0',  label: 'Hepatocellular carcinoma', category: 'hematological' },
  { code: 'C16.9',  label: 'Gastric cancer, unspecified', category: 'hematological' },
  { code: 'C18.9',  label: 'Colorectal cancer, unspecified', category: 'hematological' },
  { code: 'C83.70', label: 'Burkitt lymphoma, unspecified', category: 'hematological' },
  { code: 'C43.9',  label: 'Malignant melanoma of skin, unspecified', category: 'hematological' },
  { code: 'C44.319', label: 'Basal cell carcinoma of skin', category: 'hematological' },

  // ─── ENT / Ophthalmology (~25) ───────────────────────────────────
  { code: 'H66.9',  label: 'Otitis media, unspecified', category: 'ent_ophthal' },
  { code: 'H66.90', label: 'Otitis media, acute, unspecified ear', category: 'ent_ophthal' },
  { code: 'H66.1',  label: 'Chronic tubotympanic suppurative otitis media', category: 'ent_ophthal' },
  { code: 'H60.90', label: 'Otitis externa, unspecified', category: 'ent_ophthal' },
  { code: 'H61.21', label: 'Impacted cerumen', category: 'ent_ophthal' },
  { code: 'H72.90', label: 'Perforation of tympanic membrane, unspecified', category: 'ent_ophthal' },
  { code: 'H70.9',  label: 'Mastoiditis, unspecified', category: 'ent_ophthal' },
  { code: 'H10.0',  label: 'Bacterial conjunctivitis', category: 'ent_ophthal' },
  { code: 'H10.11', label: 'Viral conjunctivitis', category: 'ent_ophthal' },
  { code: 'H10.10', label: 'Allergic conjunctivitis, unspecified', category: 'ent_ophthal' },
  { code: 'H10.9',  label: 'Conjunctivitis, unspecified', category: 'ent_ophthal' },
  { code: 'H16.00', label: 'Corneal ulcer, unspecified', category: 'ent_ophthal' },
  { code: 'S05.00XA', label: 'Corneal abrasion without foreign body', category: 'ent_ophthal' },
  { code: 'H40.21X', label: 'Acute angle-closure glaucoma', category: 'ent_ophthal' },
  { code: 'H40.11X', label: 'Open-angle glaucoma', category: 'ent_ophthal' },
  { code: 'H25.9',  label: 'Senile cataract, unspecified', category: 'ent_ophthal' },
  { code: 'H11.0',  label: 'Pterygium', category: 'ent_ophthal' },
  { code: 'H20.9',  label: 'Uveitis, unspecified', category: 'ent_ophthal' },
  { code: 'R04.0',  label: 'Epistaxis (nosebleed)', category: 'ent_ophthal' },
  { code: 'J30.9',  label: 'Allergic rhinitis, unspecified', category: 'ent_ophthal' },
  { code: 'J34.2',  label: 'Deviated nasal septum', category: 'ent_ophthal' },
  { code: 'J33.9',  label: 'Nasal polyp, unspecified', category: 'ent_ophthal' },
  { code: 'J01.90', label: 'Acute sinusitis, unspecified', category: 'ent_ophthal' },
  { code: 'J32.9',  label: 'Chronic sinusitis, unspecified', category: 'ent_ophthal' },
  { code: 'H90.5',  label: 'Sensorineural hearing loss, unspecified', category: 'ent_ophthal' },
  { code: 'H90.2',  label: 'Conductive hearing loss, unspecified', category: 'ent_ophthal' },
  { code: 'H81.09', label: "Meniere's disease", category: 'ent_ophthal' },

  // ─── Pediatric Specific (~20) ────────────────────────────────────
  { code: 'E43',    label: 'Severe acute malnutrition (SAM)', category: 'pediatric' },
  { code: 'E44.0',  label: 'Moderate acute malnutrition (MAM)', category: 'pediatric' },
  { code: 'R62.51', label: 'Failure to thrive (child)', category: 'pediatric' },
  { code: 'R62.0',  label: 'Delayed milestone in childhood', category: 'pediatric' },
  { code: 'P36.9',  label: 'Neonatal sepsis, unspecified', category: 'pediatric' },
  { code: 'P59.9',  label: 'Neonatal jaundice, unspecified', category: 'pediatric' },
  { code: 'Q89.9',  label: 'Congenital malformation, unspecified', category: 'pediatric' },
  { code: 'Q53.9',  label: 'Undescended testis, unspecified', category: 'pediatric' },
  { code: 'Q37.9',  label: 'Cleft palate with cleft lip, unspecified', category: 'pediatric' },
  { code: 'Q65.8',  label: 'Other congenital deformity of hip', category: 'pediatric' },
  { code: 'Q24.9',  label: 'Congenital malformation of heart, unspecified', category: 'pediatric' },
  { code: 'Q21.1',  label: 'Atrial septal defect', category: 'pediatric' },
  { code: 'Q21.2',  label: 'Ventricular septal defect', category: 'pediatric' },
  { code: 'Q21.3',  label: "Tetralogy of Fallot", category: 'pediatric' },
  { code: 'Q25.0',  label: 'Patent ductus arteriosus', category: 'pediatric' },
  { code: 'N39.44', label: 'Nocturnal enuresis (bedwetting)', category: 'pediatric' },
  { code: 'K56.1',  label: 'Intussusception', category: 'pediatric' },
  { code: 'K31.1',  label: 'Adult hypertrophic pyloric stenosis (also infant)', category: 'pediatric' },
  { code: 'Z28.3',  label: 'Immunization not carried out', category: 'pediatric' },
  { code: 'E55.0',  label: 'Rickets, active', category: 'pediatric' },

  // ─── General / Constitutional (~20) ──────────────────────────────
  { code: 'R50.9',  label: 'Fever, unspecified', category: 'general' },
  { code: 'R53',    label: 'Malaise and fatigue', category: 'general' },
  { code: 'R10.9',  label: 'Unspecified abdominal pain', category: 'general' },
  { code: 'R05.9',  label: 'Cough, unspecified', category: 'general' },
  { code: 'R07.9',  label: 'Chest pain, unspecified', category: 'general' },
  { code: 'R52',    label: 'Pain, unspecified', category: 'general' },
  { code: 'R11.10', label: 'Vomiting, unspecified', category: 'general' },
  { code: 'R19.7',  label: 'Diarrhea, unspecified', category: 'general' },
  { code: 'R45.1',  label: 'Restlessness and agitation', category: 'general' },
  { code: 'R41.0',  label: 'Confusion, unspecified', category: 'general' },
  { code: 'R40.0',  label: 'Somnolence (drowsiness)', category: 'general' },
  { code: 'R55',    label: 'Syncope and collapse', category: 'general' },
  { code: 'R21',    label: 'Rash and other nonspecific skin eruption', category: 'general' },
  { code: 'R63.0',  label: 'Anorexia (loss of appetite)', category: 'general' },
  { code: 'R63.4',  label: 'Abnormal weight loss', category: 'general' },
  { code: 'R63.5',  label: 'Abnormal weight gain', category: 'general' },
  { code: 'R00.2',  label: 'Palpitations', category: 'general' },
  { code: 'R06.0',  label: 'Dyspnea (shortness of breath)', category: 'general' },
  { code: 'R06.2',  label: 'Wheezing', category: 'general' },
  { code: 'R04.0',  label: 'Epistaxis (nosebleed)', category: 'general' },
  { code: 'R00.0',  label: 'Tachycardia, unspecified', category: 'general' },
  { code: 'R00.1',  label: 'Bradycardia, unspecified', category: 'general' },
  { code: 'R09.0',  label: 'Asphyxia and hypoxemia', category: 'general' },
  { code: 'Z00.0',  label: 'Encounter for general adult medical examination', category: 'general' },
  { code: 'Z71.89', label: 'Counseling, other specified', category: 'general' },
]

// Category labels for grouping in the dropdown
export const DIAGNOSIS_CATEGORIES = {
  respiratory: 'Respiratory',
  cardiovascular: 'Cardiovascular',
  endocrine: 'Endocrine / Metabolic',
  gastrointestinal: 'Gastrointestinal',
  infectious: 'Infectious Diseases',
  neurological: 'Neurological',
  musculoskeletal: 'Musculoskeletal',
  genitourinary: 'Genitourinary',
  maternal: "Maternal / Women's Health",
  psychiatric: 'Mental Health',
  dermatological: 'Skin / Dermatological',
  hematological: 'Hematological / Oncological',
  ent_ophthal: 'ENT / Ophthalmology',
  pediatric: 'Pediatric',
  general: 'General / Symptoms',
}

// Look up a diagnosis by ICD code
export function getDiagnosisByCode(code) {
  return DIAGNOSIS_CATALOG.find((d) => d.code === code) || null
}

// Look up a diagnosis by label (case-insensitive partial match)
export function findDiagnosisByLabel(label) {
  if (!label) return null
  const lower = label.toLowerCase()
  return (
    DIAGNOSIS_CATALOG.find((d) => d.label.toLowerCase() === lower) ||
    DIAGNOSIS_CATALOG.find((d) => d.label.toLowerCase().includes(lower)) ||
    null
  )
}